kind: Deployment
apiVersion: apps/v1
metadata:
  name: database
  namespace: itonk-ap1-gr14
  selfLink: /apis/apps/v1/namespaces/itonk-ap1-gr14/deployments/database
  uid: 2f799fa2-a90f-4d15-8c30-76e4c9e9d252
  resourceVersion: '123270216'
  generation: 10
  creationTimestamp: '2020-03-18T10:22:09Z'
  labels:
    app: database
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2020-03-18T10:22:09Z","generation":5,"labels":{"app":"database"},"name":"database","namespace":"itonk-ap1-gr14","resourceVersion":"122231184","selfLink":"/apis/apps/v1/namespaces/itonk-ap1-gr14/deployments/database","uid":"2f799fa2-a90f-4d15-8c30-76e4c9e9d252"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"database"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"database"}},"spec":{"containers":[{"env":[{"name":"MSSQL_DATA_DIR","value":"/var/opt/mssql/mdf"},{"name":"MSSQL_LOG_DIR","value":"/var/opt/mssql/ldf"}],"image":"docker.io/berthelmaster0802/dbgrp14letsgo","name":"dbgrp14letsgo","volumeMounts":[{"mountPath":"/var/opt/mssql","name":"mssql-base-volume"},{"mountPath":"/var/opt/mssql/ldf","name":"mssql-ldf-volume"},{"mountPath":"/var/opt/mssql/mdf","name":"mssql-mdf-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"mssql-base-volume","persistentVolumeClaim":{"claimName":"mssql-base-volume"}},{"name":"mssql-mdf-volume","persistentVolumeClaim":{"claimName":"mssql-mdf-volume"}},{"name":"mssql-ldf-volume","persistentVolumeClaim":{"claimName":"mssql-ldf-volume","imagePullPolicy":"Always","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-03-18T10:22:09Z","lastUpdateTime":"2020-03-18T10:22:13Z","message":"ReplicaSet
      \"database-5684db4664\" has successfully
      progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2020-03-20T11:39:19Z","lastUpdateTime":"2020-03-20T11:39:19Z","message":"Deployment
      has minimum
      availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":5,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: database
    spec:
      containers:
        - name: dbgrp14letsgo
          image: docker.io/berthelmaster0802/dbgrp14letsgo
          env:
          - name: MSSQL_DATA_DIR
            value: /var/opt/mssql/mdf
          - name: MSSQL_LOG_DIR
            value: /var/opt/mssql/ldf  
          volumeMounts:
          - name: mssql-base-volume
            mountPath: /var/opt/mssql
          - name: mssql-ldf-volume
            mountPath: /var/opt/mssql/ldf
          - name: mssql-mdf-volume
            mountPath: /var/opt/mssql/mdf
      volumes:
      - name: mssql-base-volume
        persistentVolumeClaim:
          claimName: mssql-base-volume
      - name: mssql-mdf-volume
        persistentVolumeClaim:
          claimName: mssql-mdf-volume
      - name: mssql-ldf-volume
        persistentVolumeClaim:
          claimName: mssql-ldf-volume            
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 5
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-03-22T22:39:35Z'
      lastTransitionTime: '2020-03-22T22:39:35Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-03-22T23:18:52Z'
      lastTransitionTime: '2020-03-18T10:22:09Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "database-5684db4664" has successfully progressed.