// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONK_Delprojekt1_Backend.Data;

namespace ONK_Delprojekt1_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200309135138_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ONK_Delprojekt1_Backend.Models.Haandvaerker", b =>
                {
                    b.Property<int>("HaandvaerkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HVAnsaettelsedato")
                        .HasColumnType("datetime2");

                    b.Property<string>("HVEfternavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HVFagomraade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HVFornavn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HaandvaerkerId");

                    b.ToTable("Haandvaerkers");

                    b.HasData(
                        new
                        {
                            HaandvaerkerId = 1,
                            HVAnsaettelsedato = new DateTime(2020, 3, 9, 14, 51, 37, 194, DateTimeKind.Local).AddTicks(9888),
                            HVEfternavn = "Hansen",
                            HVFagomraade = "Byggeri",
                            HVFornavn = "Hans"
                        });
                });

            modelBuilder.Entity("ONK_Delprojekt1_Backend.Models.Vaerktoej", b =>
                {
                    b.Property<long>("VTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LiggerIvtk")
                        .HasColumnType("int");

                    b.Property<int?>("LiggerIvtkNavigationVTKId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VTAnskaffet")
                        .HasColumnType("datetime2");

                    b.Property<string>("VTFabrikat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTSerienr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VTId");

                    b.HasIndex("LiggerIvtkNavigationVTKId");

                    b.ToTable("Vaerktoejs");

                    b.HasData(
                        new
                        {
                            VTId = 1L,
                            VTAnskaffet = new DateTime(2020, 3, 9, 14, 51, 37, 203, DateTimeKind.Local).AddTicks(494),
                            VTFabrikat = "Test fabrikat",
                            VTModel = "QC521",
                            VTSerienr = "2011064688",
                            VTType = "Skruetrækker"
                        });
                });

            modelBuilder.Entity("ONK_Delprojekt1_Backend.Models.Vaerktoejskasse", b =>
                {
                    b.Property<int>("VTKId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EjesAfNavigationHaandvaerkerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VTKAnskaffet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VTKEjesAf")
                        .HasColumnType("int");

                    b.Property<string>("VTKFabrikat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTKFarve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTKModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTKSerienummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VTKId");

                    b.HasIndex("EjesAfNavigationHaandvaerkerId");

                    b.ToTable("Vaerktoejskasses");

                    b.HasData(
                        new
                        {
                            VTKId = 1,
                            VTKAnskaffet = new DateTime(2020, 3, 9, 14, 51, 37, 204, DateTimeKind.Local).AddTicks(2142),
                            VTKFabrikat = "Test fabrikat",
                            VTKFarve = "Blaa",
                            VTKModel = "AN521",
                            VTKSerienummer = "2019064688"
                        });
                });

            modelBuilder.Entity("ONK_Delprojekt1_Backend.Models.Vaerktoej", b =>
                {
                    b.HasOne("ONK_Delprojekt1_Backend.Models.Vaerktoejskasse", "LiggerIvtkNavigation")
                        .WithMany("Vaerktoej")
                        .HasForeignKey("LiggerIvtkNavigationVTKId");
                });

            modelBuilder.Entity("ONK_Delprojekt1_Backend.Models.Vaerktoejskasse", b =>
                {
                    b.HasOne("ONK_Delprojekt1_Backend.Models.Haandvaerker", "EjesAfNavigation")
                        .WithMany("Vaerktoejskasse")
                        .HasForeignKey("EjesAfNavigationHaandvaerkerId");
                });
#pragma warning restore 612, 618
        }
    }
}
